sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.2

before_install:
  - docker-compose rm --force
  - docker-compose build
  - docker version
  - docker-compose version
  - docker ps
env:
  - RAILS_ENV=test
script:
  - docker-compose run rake
