---
base:
  build: .
  volumes:
    - ".:/app"
  ports:
    - "80:3000"

web:
  extends:
    file: docker-compose.yml
    service: base
  environment:
  links:
    - devdb
  command: rails s -b 0.0.0.0

devdb:
  image: postgres:9.4
  environment:
    POSTGRES_USER: session_development
    POSTGRES_PASSWORD: thepassword
  ports:
    - "5433:5432"

rake:
  extends:
    file: docker-compose.yml
    service: base
  environment:
    RACK_ENV: test
  links:
    - testdb
  command: rake

testdb:
  image: postgres:9.4
  environment:
    POSTGRES_USER: session_test
    POSTGRES_PASSWORD: thepassword
  ports:
    - "5433:5432"
